global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  
  - job_name: 'flower'
    scrape_interval: 5s
    static_configs:
      - targets: ['flower:5555']

  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
      - targets: ['celery-flask:5000']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
